//! What a run *is*: a seed, a duration, a set of nodes, and a script.
//!
//! A scenario is plain data with no behaviour, which is the whole trick. It can
//! be written by hand in a test, generated by a fuzzer, recovered from a
//! recording, or exported as a conformance vector, and every one of those paths
//! produces the same run.

use crate::clock::Ppm;
use crate::net::{NetFaults, NodeId};

/// One simulated device.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct NodeSpec {
    pub id: NodeId,
    /// How many LEDs this node drives. Zero is legal and means a node with no
    /// render capability — a sensor or a control surface. Rule 3 says mapping
    /// is a pure upgrade; rule "render is one capability among many" says a
    /// non-rendering node must not be a special case anywhere.
    pub pixel_count: usize,
    /// Clock offset at boot.
    pub skew_us: i64,
    /// Crystal error in ppm.
    pub drift_ppm: Ppm,
    /// Storage budget, so a scenario can test a node running out of flash.
    pub storage_capacity: usize,
}

impl NodeSpec {
    /// A well-behaved node with a perfect clock.
    pub fn new(id: NodeId, pixel_count: usize) -> Self {
        Self {
            id,
            pixel_count,
            skew_us: 0,
            drift_ppm: 0,
            storage_capacity: crate::storage::DEFAULT_CAPACITY,
        }
    }

    /// The same node with a wrong clock. Every mesh has these; a scenario in
    /// which every clock already agrees proves nothing about time sync.
    pub fn with_clock_error(mut self, skew_us: i64, drift_ppm: Ppm) -> Self {
        self.skew_us = skew_us;
        self.drift_ppm = drift_ppm;
        self
    }

    /// The same node with a smaller flash partition.
    pub fn with_storage_capacity(mut self, capacity: usize) -> Self {
        self.storage_capacity = capacity;
        self
    }
}

/// Something the harness does to the world at a named virtual time.
///
/// Deliberately an enum rather than a closure: a closure cannot be written to a
/// recording, exported as a vector, or compared between two runs, and those
/// three are what the harness is for. New fault kinds are new variants — that
/// is the extension seam.
#[derive(Clone, PartialEq, Eq, Debug)]
pub enum Op {
    /// Wake a node. Until the state machines land this is the only `Event` the
    /// core can be handed.
    Tick(NodeId),
    /// Have a node transmit a datagram. Stands in for the sends the real state
    /// machines will make once they exist, and stays useful afterwards as a way
    /// to inject traffic from something that is not a simulated node at all —
    /// an Art-Net source, a phone, a hostile packet.
    Send {
        from: NodeId,
        to: NodeId,
        bytes: Vec<u8>,
    },
    /// The same, to a multicast group. Channels ride multicast.
    Multicast {
        from: NodeId,
        group: u8,
        bytes: Vec<u8>,
    },
    /// A node joins a multicast group.
    Join { node: NodeId, group: u8 },
    /// Yank the power. Inbox and inbound traffic are lost; storage survives.
    Kill(NodeId),
    /// Power a node back up. `wipe_storage` is the difference between a reboot
    /// and a factory reset, and they exercise completely different rejoin
    /// paths.
    Revive { node: NodeId, wipe_storage: bool },
    /// Cut two nodes off from each other.
    Partition(NodeId, NodeId),
    /// Restore one link.
    Heal(NodeId, NodeId),
    /// Restore every link.
    HealAll,
    /// Split the mesh in two. `left` and `right` may overlap with neither.
    Split {
        left: Vec<NodeId>,
        right: Vec<NodeId>,
    },
    /// Replace the network fault model — "the WiFi got bad".
    SetFaults(NetFaults),
    /// Move a node's clock offset.
    Skew { node: NodeId, offset_us: i64 },
    /// Change a node's crystal error.
    Drift { node: NodeId, ppm: Ppm },
    /// Feed a correction to a node's clock. Slewed, never stepped.
    Discipline { node: NodeId, offset_us: i64 },
    /// Present a flat frame at `level`. A placeholder for the render loop,
    /// which does not exist yet — it exists so that frame recording, the frame
    /// digest and the "never dark" assertions are exercised now rather than
    /// being written blind later.
    Present { node: NodeId, level: u16 },
    /// Write a record to a node's flash.
    Store {
        node: NodeId,
        key: String,
        value: Vec<u8>,
    },
    /// Erase a record.
    Erase { node: NodeId, key: String },
}

/// An op with the virtual time it happens at.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct ScriptedOp {
    pub at_us: u64,
    pub op: Op,
}

/// A complete, self-contained description of a run.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Scenario {
    /// The seed. Together with the script it determines the run completely —
    /// that is the entire contract, and it is what turns an irreproducible
    /// distributed bug into a checked-in test.
    pub seed: u64,
    /// How long the run lasts in virtual microseconds. Cheap: a day costs the
    /// same as a millisecond unless something is scheduled in between.
    pub duration_us: u64,
    pub nodes: Vec<NodeSpec>,
    pub faults: NetFaults,
    /// The script, kept sorted by time. Ops at the same instant run in the
    /// order they were added, so a `Kill` and a `Send` on the same microsecond
    /// are not a coin flip.
    pub script: Vec<ScriptedOp>,
}

impl Scenario {
    /// An empty scenario.
    pub fn new(seed: u64, duration_us: u64) -> Self {
        Self {
            seed,
            duration_us,
            nodes: Vec::new(),
            faults: NetFaults::perfect(),
            script: Vec::new(),
        }
    }

    /// Add a node.
    pub fn with_node(mut self, spec: NodeSpec) -> Self {
        self.nodes.push(spec);
        self
    }

    /// Add `count` plain nodes with ids `1..=count`, each driving `pixels`.
    pub fn with_nodes(mut self, count: NodeId, pixels: usize) -> Self {
        for id in 1..=count {
            self.nodes.push(NodeSpec::new(id, pixels));
        }
        self
    }

    /// Set the initial fault model.
    pub fn with_faults(mut self, faults: NetFaults) -> Self {
        self.faults = faults;
        self
    }

    /// Schedule an op.
    pub fn at(mut self, at_us: u64, op: Op) -> Self {
        self.script.push(ScriptedOp { at_us, op });
        self
    }

    /// Schedule a repeating op — every `period_us` from `start_us` until
    /// `end_us` exclusive. Building a tick train by hand is the most common
    /// thing a scenario does and the easiest to get subtly wrong.
    pub fn every(
        mut self,
        start_us: u64,
        period_us: u64,
        end_us: u64,
        mut make: impl FnMut(u64) -> Op,
    ) -> Self {
        if period_us == 0 {
            return self;
        }
        let mut t = start_us;
        while t < end_us {
            self.script.push(ScriptedOp {
                at_us: t,
                op: make(t),
            });
            t += period_us;
        }
        self
    }

    /// Put the script in time order, preserving insertion order within an
    /// instant. `sort_by_key` is stable, which is the property being relied on:
    /// a run must not depend on how the script happened to be assembled.
    pub fn normalise(mut self) -> Self {
        self.script.sort_by_key(|s| s.at_us);
        self
    }

    /// The ids of every node, in order.
    pub fn node_ids(&self) -> Vec<NodeId> {
        self.nodes.iter().map(|n| n.id).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_scenario_builds_up() {
        let s = Scenario::new(1, 1_000)
            .with_node(NodeSpec::new(1, 8))
            .with_node(NodeSpec::new(2, 0).with_clock_error(500, -20))
            .with_faults(NetFaults::lossy_wifi())
            .at(10, Op::Tick(1))
            .at(20, Op::Kill(2));
        assert_eq!(s.seed, 1);
        assert_eq!(s.duration_us, 1_000);
        assert_eq!(s.node_ids(), vec![1, 2]);
        assert_eq!(s.nodes[1].skew_us, 500);
        assert_eq!(s.nodes[1].drift_ppm, -20);
        assert_eq!(s.faults, NetFaults::lossy_wifi());
        assert_eq!(s.script.len(), 2);
    }

    #[test]
    fn with_nodes_numbers_from_one() {
        let s = Scenario::new(1, 1).with_nodes(3, 4);
        assert_eq!(s.node_ids(), vec![1, 2, 3]);
        assert!(s.nodes.iter().all(|n| n.pixel_count == 4));
    }

    #[test]
    fn storage_capacity_is_settable() {
        let n = NodeSpec::new(1, 0).with_storage_capacity(128);
        assert_eq!(n.storage_capacity, 128);
        assert_eq!(
            NodeSpec::new(1, 0).storage_capacity,
            crate::storage::DEFAULT_CAPACITY
        );
    }

    #[test]
    fn every_builds_a_train() {
        let s = Scenario::new(1, 100).every(0, 25, 100, |_| Op::Tick(1));
        let times: Vec<u64> = s.script.iter().map(|o| o.at_us).collect();
        assert_eq!(times, vec![0, 25, 50, 75]);
    }

    #[test]
    fn every_carries_the_time_into_the_op() {
        let s = Scenario::new(1, 10).every(0, 5, 10, |t| Op::Present {
            node: 1,
            level: t as u16,
        });
        assert_eq!(s.script[1].op, Op::Present { node: 1, level: 5 });
    }

    #[test]
    fn a_zero_period_train_is_empty_rather_than_infinite() {
        let s = Scenario::new(1, 10).every(0, 0, 10, |_| Op::Tick(1));
        assert!(s.script.is_empty());
    }

    #[test]
    fn an_empty_window_produces_nothing() {
        let s = Scenario::new(1, 10).every(10, 5, 10, |_| Op::Tick(1));
        assert!(s.script.is_empty());
    }

    #[test]
    fn normalise_sorts_but_keeps_insertion_order_within_an_instant() {
        let s = Scenario::new(1, 10)
            .at(5, Op::Tick(1))
            .at(1, Op::Tick(2))
            .at(5, Op::Tick(3))
            .normalise();
        let ops: Vec<&Op> = s.script.iter().map(|o| &o.op).collect();
        assert_eq!(ops, vec![&Op::Tick(2), &Op::Tick(1), &Op::Tick(3)]);
    }

    #[test]
    fn ops_compare_structurally() {
        assert_eq!(
            Op::Send {
                from: 1,
                to: 2,
                bytes: vec![1, 2]
            },
            Op::Send {
                from: 1,
                to: 2,
                bytes: vec![1, 2]
            }
        );
        assert_ne!(Op::Tick(1), Op::Tick(2));
        assert_ne!(Op::HealAll, Op::Heal(1, 2));
    }
}
